### ISSUE TITLE
TEST: Repositories for Big Files : analysis of the options (Meta)

### ISSUE THREAD

**Issue by evaristoc** [freeCodeCamp/open-data#19]
Our plan is:

>Stick to 1 or 2 data storages that balance:
>* the best storage in size
>* the best visibility to the dataset
>* the best visibility to fCC
>* the best of the additional features that better help the user
>* the simplest procedures
>* the less disruptive to users
>* comply with the open data philosophy

Options:
- [x] Testing datadotworld SEE https://github.com/freeCodeCamp/open-data/issues/6
- [ ] Testing dat project SEE https://github.com/freeCodeCamp/open-data/issues/15
- [x] Testing BitTorrent SEE https://github.com/freeCodeCamp/open-data/issues/11
- [x] Evaluating `git lfs` SEE: https://github.com/freeCodeCamp/open-data/issues/10
- [ ] Evaluating http://datahub.io/; eg. https://old.datahub.io/dataset/dmoz
- [ ] Evaluating https://datahub.csail.mit.edu/www/

---

## Task 1
- [x] ~Prepare a comparison table for all the explored options~ overkill
